name: coda_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.3
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  lint: ^1.8.2
  mockito: ^5.2.0
  provider: ^6.0.3
  simple_animations: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/upload-coda.jpg
    - assets/images/profile-pic.png
