// Mocks generated by Mockito 5.2.0 from annotations
// in coda_test/test/features/clients/presentation/bloc/clients/client_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:coda_test/core/error/failure.dart' as _i6;
import 'package:coda_test/core/use_cases/use_case.dart' as _i8;
import 'package:coda_test/features/clients/domain/entities/client.dart' as _i7;
import 'package:coda_test/features/clients/domain/repository/client_repository.dart'
    as _i2;
import 'package:coda_test/features/clients/domain/use_cases/add_client_use_case.dart'
    as _i10;
import 'package:coda_test/features/clients/domain/use_cases/delete_client_use_case.dart'
    as _i12;
import 'package:coda_test/features/clients/domain/use_cases/edit_client_use_case.dart'
    as _i13;
import 'package:coda_test/features/clients/domain/use_cases/get_clients_use_case.dart'
    as _i4;
import 'package:coda_test/features/clients/domain/use_cases/params/client_params.dart'
    as _i11;
import 'package:coda_test/features/clients/presentation/bloc/clients/client_bloc.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClientRepository_0 extends _i1.Fake implements _i2.ClientRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetClientsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetClientsUseCase extends _i1.Mock implements _i4.GetClientsUseCase {
  MockGetClientsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClientRepository get clientRepository =>
      (super.noSuchMethod(Invocation.getter(#clientRepository),
          returnValue: _FakeClientRepository_0()) as _i2.ClientRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ClientData>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i7.ClientData>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i7.ClientData>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ClientData>>>);
}

/// A class which mocks [ShowMoreInClientsList].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowMoreInClientsList extends _i1.Mock
    implements _i9.ShowMoreInClientsList {
  MockShowMoreInClientsList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.ClientData> get clientsList =>
      (super.noSuchMethod(Invocation.getter(#clientsList),
          returnValue: <_i7.ClientData>[]) as List<_i7.ClientData>);
  @override
  List<_i7.ClientData> get clientsToShowList =>
      (super.noSuchMethod(Invocation.getter(#clientsToShowList),
          returnValue: <_i7.ClientData>[]) as List<_i7.ClientData>);
  @override
  List<Object> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object>[])
          as List<Object>);
}

/// A class which mocks [AddClientUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddClientUseCase extends _i1.Mock implements _i10.AddClientUseCase {
  MockAddClientUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClientRepository get clientRepository =>
      (super.noSuchMethod(Invocation.getter(#clientRepository),
          returnValue: _FakeClientRepository_0()) as _i2.ClientRepository);
  @override
  set clientRepository(_i2.ClientRepository? _clientRepository) => super
      .noSuchMethod(Invocation.setter(#clientRepository, _clientRepository),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ClientData>> call(
          _i11.ClientParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.ClientData>>.value(
              _FakeEither_1<_i6.Failure, _i7.ClientData>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.ClientData>>);
}

/// A class which mocks [DeleteClientUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteClientUseCase extends _i1.Mock
    implements _i12.DeleteClientUseCase {
  MockDeleteClientUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClientRepository get clientRepository =>
      (super.noSuchMethod(Invocation.getter(#clientRepository),
          returnValue: _FakeClientRepository_0()) as _i2.ClientRepository);
  @override
  set clientRepository(_i2.ClientRepository? _clientRepository) => super
      .noSuchMethod(Invocation.setter(#clientRepository, _clientRepository),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(int? clientId) =>
      (super.noSuchMethod(Invocation.method(#call, [clientId]),
              returnValue: Future<_i3.Either<_i6.Failure, void>>.value(
                  _FakeEither_1<_i6.Failure, void>()))
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [EditClientUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditClientUseCase extends _i1.Mock implements _i13.EditClientUseCase {
  MockEditClientUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClientRepository get clientRepository =>
      (super.noSuchMethod(Invocation.getter(#clientRepository),
          returnValue: _FakeClientRepository_0()) as _i2.ClientRepository);
  @override
  set clientRepository(_i2.ClientRepository? _clientRepository) => super
      .noSuchMethod(Invocation.setter(#clientRepository, _clientRepository),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ClientData>> call(
          _i11.ClientParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.ClientData>>.value(
              _FakeEither_1<_i6.Failure, _i7.ClientData>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.ClientData>>);
}
